# Generated by Django 2.1.5 on 2019-04-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
    ]
